[tasks.clean]
description = "clean: remove the target directory"
category = "Build"
command = "cargo"
args = ["clean"]

[tasks.check]
description = "build: analyze the workspace and report errors, but don't build object files"
category = "Build"
env = { "SQLX_OFFLINE" = "true" }
command = "cargo"
args = ["check"]

[tasks.build]
description = "build: compile the workspace"
category = "Build"
command = "cargo"
args = ["build"]

[tasks.test]
description = "test: run the tests"
category = "Check"
env = { "SQLX_OFFLINE" = "true" }
command = "cargo"
args = ["test", "--no-fail-fast", "--", "--test-threads", "2"]

[tasks.docs]
description = "docs: generate the rustdoc"
env = { "SQLX_OFFLINE" = "true" }
command = "cargo"
args = ["doc", "--no-deps"]

[tasks.fmt-check]
description = "format: check the sources formatting"
category = "Check"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--check"]

[tasks.clippy]
description = "clippy: run the rust linter"
category = "Check"
env = { "SQLX_OFFLINE" = "true" }
install_crate = { crate_name = "clippy", rustup_component_name = "clippy", binary = "cargo-clippy", test_arg = "--help" }
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]
