name: Micronaut R2DBC CI
on:
  push:
    paths:
      - '.github/workflows/java-micronaut-r2dbc-ci.yaml'
      - 'java-micronaut-r2dbc/**'
      - 'java-shared-library/**'
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Compile the project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: java-micronaut-r2dbc:build -x check

      - name: Checks that sourcecode satisfies formatting rules
        uses: gradle/gradle-build-action@v2
        with:
          arguments: java-micronaut-r2dbc:spotlessCheck

      - name: Run the unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: java-shared-library:test java-micronaut-r2dbc:test

      - uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: |
            **/build/reports

  docker:
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref_name == 'main'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the container image
        uses: gradle/gradle-build-action@v2
        with:
          arguments: java-micronaut-r2dbc:dockerBuild

      - name: Push the container image
        run: |
          docker push ghcr.io/carlomicieli/consolemania-micronaut-r2dbc
