name: Actix Web CI
on:
  push:
    paths:
      - '.github/workflows/rust-actix-web-ci.yaml'
      - 'rust-actix-web/**'
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_MAKE_RUN_CODECOV: true
  SQLX_OFFLINE: true
  REGISTRY: ghcr.io
  IMAGE_NAME: consolemania-actix-web

jobs:
  checks:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Get current MSRV from Cargo.toml
        id: get-msrv
        run: echo "MSRV=$(cat ./Cargo.toml | grep rust-version | sed 's/.* = "//; s/"//')" >> $GITHUB_OUTPUT

      - name: Get current rustc version
        id: get-rustc-version
        run: echo "RUSTC_VERSION=$(rustc --version | cut -c 7-10)" >> $GITHUB_OUTPUT

      - name: Install rust toolchain
        run: |
          rustup set profile minimal
          rustup toolchain install stable
        if: ${{ steps.get-rustc-version.outputs.RUSTC_VERSION != steps.get-msrv.outputs.MSRV }}

      - name: Install cargo make
        run: cargo install cargo-make@0.36.5

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Toolchain info
        run: |
          rustc --version
          cargo --version --verbose
          cargo make --version

      - name: Run cargo check
        run: cargo make check
        working-directory: ./rust-actix-web

      - name: Check formatting with rustfmt
        run: cargo make fmt-check
        working-directory: ./rust-actix-web

      - name: Linting with Clippy
        run: cargo make clippy
        working-directory: ./rust-actix-web

  docker:
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref_name == 'main'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha

      - name: Build and push Docker image (server)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .docker/rust-actix-web.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
